// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5571.RobotFinal.subsystems;

import org.usfirst.frc5571.RobotFinal.RobotMap;
import org.usfirst.frc5571.RobotFinal.commands.*;

import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Cameras extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CameraServer server;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands
    
    public void clampCamera() {
    	server = CameraServer.getInstance();
    	server.setQuality(75);
    	server.startAutomaticCapture("cam0");
    	
    }
    
//    public void elevCamera() {
//    	server = CameraServer.getInstance();
//    	server.setQuality(50);
//    	server.startAutomaticCapture("cam1");
//    	
//    }

	
	

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new Camera());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

//Unhandled exception: VisionException [com.ni.vision.VisionException: IMAQdxError: -1074360310: Camera is already in use.] at [com.ni.vision.NIVision._IMAQdxOpenCamera(Native Method),
//                                                                                                                              com.ni.vision.NIVision.IMAQdxOpenCamera(NIVision.java:24455), 
//                                                                                                                              edu.wpi.first.wpilibj.vision.USBCamera.openCamera(USBCamera.java:61),
//                                                                                                                              edu.wpi.first.wpilibj.vision.USBCamera.<init>(USBCamera.java:54),
//                                                                                                                              edu.wpi.first.wpilibj.CameraServer.startAutomaticCapture(CameraServer.java:167),
//                                                                                                                              org.usfirst.frc5571.RobotFinal.subsystems.Cameras.clampCamera(Cameras.java:36), 
//                                                                                                                              org.usfirst.frc5571.RobotFinal.commands.Camera.execute(Camera.java:38),
//                                                                                                                              edu.wpi.first.wpilibj.command.Command.run(Command.java:217),
//                                                                                                                              edu.wpi.first.wpilibj.command.Scheduler.run(Scheduler.java:215),
//                                                                                                                              org.usfirst.frc5571.RobotFinal.Robot.teleopPeriodic(Robot.java:107),
//                                                                                                                              edu.wpi.first.wpilibj.IterativeRobot.startCompetition(IterativeRobot.java:150),
//                                                                                                                              edu.wpi.first.wpilibj.RobotBase.main(RobotBase.java:234)]
//

