// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5571.RobotFinal.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.WaitCommand;

import org.usfirst.frc5571.RobotFinal.Robot;
import org.usfirst.frc5571.RobotFinal.RobotMap;
import org.usfirst.frc5571.RobotFinal.subsystems.Elevator;


/**
 * Bobby Gintz
 * 
 * This is a simple autonomous command group that sequences between a number of planned moves from a given position
 * After determining reasonable values for 90 degree turns and distance traveled in a straight line they can be
 * coded here.  
 * 
 * Note:  there is no compensation for drift so straight line distances may not be straight
 * 
 * Also:  Use caution when testing this command.  Be prepared to hit the SPACE bar on the driver station
 * which will cause an E-STOP
 */




public class  AutonomousLindGambit extends CommandGroup {
	// Flag to end the command
	public Boolean autoDone = false;
	//Boolean autoDriveCommandInProgress = false;

	// Scaling factors to adjust drive sensitivity during autonomous to simulate Joystick deflections. 
	static double AUTO_FAST_DRIVE_MAGNITUDE_SCALE = 0.6;
	static double AUTO_FAST_DRIVE_TWIST_SCALE = 0.5;
	static double AUTO_FINE_DRIVE_MAGNITUDE_SCALE = 0.4;
	static double AUTO_FINE_DRIVE_TWIST_SCALE = 0.3;


	static double DRIVE_TO_AUTO	= 10.0;	/* 1.2 seconds to go from start posision to auto zone */
	static double TIME_TO_ROTATE_90_DEGREES = 0.67;  /*  0.67 seconds estimated to rotate left */

	public AutonomousLindGambit() {
		

		// Use requires() here to declare subsystem dependencies
		// eg. requires(chassis);

		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		
		/* Commands below use the mecanumDriveAutoFine() method of the drive train
		 * this mthod takes three doubles:  magnitude, direction, and rotation.
		 * 
		 * The commands run for as long as the duration specified in the call to the command
		 */
		
		
		/************* Bulldogs Defense Requires The Elevator to be pre placed **************************/
		if (Robot.elevator.downLimitReached()){  /* On case drive team forgets to raise the elevator */
			addSequential(new MoveElevatorToPositionCommand(32000, 10)); /* raise to clear totes in landfill 16000 picks up*/
		}
		addSequential(new AutoDriveCommand(0,0,3,0.4));  // Good 90 degree turn timing
		//addSequential(new AutoDriveCommand(0,0,1,1.5));  // Good 90 degree turn timing
		addSequential(new OpenGripperCommand(5));
		addSequential(new AutoDriveCommand(1, 0, 0, .5));
		/************* Bulldogs Defense **************************/
	
	}
}

	